version: '3.8'

services:
  backend:
    image: gorjanbogoevski/recipenest-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: gorjanbogoevski/recipenest-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"