version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: gorjanbogoevski/recipenest-backend:v1
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    image: gorjanbogoevski/recipenest-frontend:v1
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data:
