apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: recipes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gorjanbogoevski/recipenest-backend-k8s:v2
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: recipes-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: recipes-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_URI
              value: mongodb://mongo-0.mongo.recipes.svc.cluster.local:27017,mongo-1.mongo.recipes.svc.cluster.local:27017/?replicaSet=rs0&authSource=admin


---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: recipes
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
