apiVersion: v1
kind: Secret
metadata:
  name: recipes-secret
  namespace: recipes
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "12345"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-keyfile-secret
  namespace: recipes
type: Opaque
stringData:
  mongo-keyfile: |
    WWueYK6HmB5W0PkOIeWm927TafDtsJtBZM4BzD5HjrF9hbqAnBxuRcejNHeU0I90
    GzRZsYOrLWphhRROcjECMLGWdJbssPqe1UiEQIdtVZ7kAiXPqXwnSBEjcXb1V6jA
    Egyo1dKMPIonrx1WZVb8ETaMyUbra5XxhRxKr1gyMNWJQEKrUibwiMLPu1fw0HUv
    AZRhwIITVgVk7pUlFkB949Nhvce6LtTIkR/UsJg9/1OVEAXB6q8it7DVVY5Uzcfz
    68H+DPS3Sfiz2CtfM/Lr/jJyNUZaKS8tba5JxfsEPyJg0uqO2cq2AusMA2B0UlSs
    z8LMRhpjYvmmRG8Zp6pUl2ugySzKhpcedIf5Ad2sO05ZrYyDrkQcsoCioGWwzh8o
    0U+2IIQXaPj0e8mngZxuyPgbjfBH4LZMR3Q55nL+jW+rQYrfVvWSJeERVHbS49KR
    hWJj1wVr9yI5ZUtFLP8wVdUdJ7ue4oTOHu5SMoIHrwVyrH3s7a511XDF7RM15hUu
    M6f0BVkjC6bPOeLMacC+EsyozR0ag0oOl9/BuhKwx363/5JdaTLje1oLBtBM8j+e
    wSc4pMpP8ys0pyMO9fdeixmwzEA7Ah/OhLkUc0w/h/nixyJVCTT5eJ95Y9pxhC2X
    y7TfFkOQ3S4CfUQweBz/RsTm4GCMBLhijQY6drt57Vb3kjweHPlBGXyAnmhJps4u
    bXEnArkRGuQoX/1DLJ3Xr9wDfYUEQcQ4ezMQwzJgwoFmadXfWE1HnV2En/8RbTBX
    VtoQKLyWSdxO8avqFXynluBEwlPdawjNYVJeGFobiRut/jeeoh3CTLP7Hc40OEVB
    arjZL1bNgqneJ6YnMpCeQC0xzlLQW3sDEoX7ETk1es/kYHfAJe1ku2eMkP5IiIJA
    eCKr9Nd4fdQF89xxxAad0+mbDvmm4mlH6lr35z+6Sd3mQfXcb0WKGE43X3sETqEe
    sVeYIC++h79NRzyBgvWqibJeUd3e+mi6gdWh5tGZ565jQg+y
